services:
  web:
    build: .
    ports:
      - '3030:3030'
    environment:
      - dbCollection=cryptdata
      - dbPORT=8090
      - PORT=3030
      - dbURI=http://pocketbase
    depends_on:
      - pocketbase
  pocketbase:
    build:
      context: ./db
      args:
        dbPORT: 8090
    ports:
      - '8090:8090'
